services:

  # Public API
  public_station_api:
    build: 
      context: .
      dockerfile: src\PublicStationAPI\Dockerfile
    ports:
     - "8081:8080"
     - '4431:443'
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - PrivateStationApiUrl=http://private_station_api:8080

  # Private API
  private_station_api:
    build: 
      context: .
      dockerfile: src\PrivateStationAPI\Dockerfile
    ports:
     - "8082:8080"
     - '4430:443'
    environment:
     - ASPNETCORE_ENVIRONMENT=Development