services:

  # Public API
  public_station_api:
    build: 
      context: .
      dockerfile: src\PublicStationAPI\Dockerfile
    ports:
     - "8081:8080"
     - '4431:443'
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - PrivateStationApiUrl=http://private_station_api:8080

  # Private API
  private_station_api:
    build: 
      context: .
      dockerfile: src\PrivateStationAPI\Dockerfile
    ports:
     - "8082:8080"
     - '4430:443'
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres_db

  # database
  postgres_db:
    image: postgres
    volumes:
      - ./volume/postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"   
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  # pgamdin
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./volume/pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    