// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrivateStationAPI;

#nullable disable

namespace PrivateStationAPI.Migrations
{
    [DbContext(typeof(StationContext))]
    partial class StationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrivateStationAPI.Entities.StationDAO", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id"));

                    b.Property<string>("accessibilite_pmr")
                        .HasColumnType("text");

                    b.Property<string>("adresse_station")
                        .HasColumnType("text");

                    b.Property<bool?>("cable_t2_attache")
                        .HasColumnType("boolean");

                    b.Property<string>("code_insee_commune")
                        .HasColumnType("text");

                    b.Property<string>("condition_acces")
                        .HasColumnType("text");

                    b.Property<int?>("consolidated_code_postal")
                        .HasColumnType("integer");

                    b.Property<string>("consolidated_commune")
                        .HasColumnType("text");

                    b.Property<bool>("consolidated_is_code_insee_verified")
                        .HasColumnType("boolean");

                    b.Property<bool>("consolidated_is_lon_lat_correct")
                        .HasColumnType("boolean");

                    b.Property<float?>("consolidated_latitude")
                        .HasColumnType("real");

                    b.Property<float?>("consolidated_longitude")
                        .HasColumnType("real");

                    b.Property<string>("contact_amenageur")
                        .HasColumnType("text");

                    b.Property<string>("contact_operateur")
                        .HasColumnType("text");

                    b.Property<string>("coordonneesXY")
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("datagouv_dataset_id")
                        .HasColumnType("text");

                    b.Property<string>("datagouv_organization_or_owner")
                        .HasColumnType("text");

                    b.Property<string>("datagouv_resource_id")
                        .HasColumnType("text");

                    b.Property<string>("date_maj")
                        .HasColumnType("text");

                    b.Property<string>("date_mise_en_service")
                        .HasColumnType("text");

                    b.Property<string>("gratuit")
                        .HasColumnType("text");

                    b.Property<string>("horaires")
                        .HasColumnType("text");

                    b.Property<string>("id_pdc_itinerance")
                        .HasColumnType("text");

                    b.Property<string>("id_pdc_local")
                        .HasColumnType("text");

                    b.Property<string>("id_station_itinerance")
                        .HasColumnType("text");

                    b.Property<string>("id_station_local")
                        .HasColumnType("text");

                    b.Property<string>("implantation_station")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("nbre_pdc")
                        .HasColumnType("integer");

                    b.Property<string>("nom_amenageur")
                        .HasColumnType("text");

                    b.Property<string>("nom_enseigne")
                        .HasColumnType("text");

                    b.Property<string>("nom_operateur")
                        .HasColumnType("text");

                    b.Property<string>("nom_station")
                        .HasColumnType("text");

                    b.Property<string>("num_pdl")
                        .HasColumnType("text");

                    b.Property<string>("observations")
                        .HasColumnType("text");

                    b.Property<string>("paiement_acte")
                        .HasColumnType("text");

                    b.Property<string>("paiement_autre")
                        .HasColumnType("text");

                    b.Property<string>("paiement_cb")
                        .HasColumnType("text");

                    b.Property<string>("prise_type_2")
                        .HasColumnType("text");

                    b.Property<string>("prise_type_autre")
                        .HasColumnType("text");

                    b.Property<string>("prise_type_chademo")
                        .HasColumnType("text");

                    b.Property<string>("prise_type_combo_ccs")
                        .HasColumnType("text");

                    b.Property<string>("prise_type_ef")
                        .HasColumnType("text");

                    b.Property<float?>("puissance_nominale")
                        .HasColumnType("real");

                    b.Property<string>("raccordement")
                        .HasColumnType("text");

                    b.Property<string>("reservation")
                        .HasColumnType("text");

                    b.Property<string>("restriction_gabarit")
                        .HasColumnType("text");

                    b.Property<float?>("siren_amenageur")
                        .HasColumnType("real");

                    b.Property<string>("station_deux_roues")
                        .HasColumnType("text");

                    b.Property<string>("tarification")
                        .HasColumnType("text");

                    b.Property<string>("telephone_operateur")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
